# Podfile

inhibit_all_warnings!

target 'WatchPulse' do
  platform :ios, '12.0'

  # Use static frameworks to avoid a bunch of modern Xcode rsync/embed pain.
  use_frameworks! :linkage => :static

  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 5.0'
end

target 'WatchPulse WatchKit Extension' do
  platform :watchos, '5.0'

  use_frameworks! :linkage => :static

  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON', '~> 5.0'
end

post_install do |installer|
  # Xcode sandboxing can break CocoaPods rsync framework copy scripts with
  # "Operation not permitted". Force it off for Pods and the user project.
  projects = [installer.pods_project]

  installer.aggregate_targets.each do |aggregate_target|
    projects << aggregate_target.user_project if aggregate_target.respond_to?(:user_project)
  end

  projects.compact.uniq.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end

    project.save
  end
end